import { describe, expect, it } from 'vitest'

import {
  applyClaimGroup,
  contextValueSet,
  forceUnverifiedDiscipline,
  guardClaimValue,
  mergeSkeletonWithModel,
  parseJsonLoose,
} from '@/agents/llmBridge'
import { buildEvidenceRegister } from '@/agents/deskResearcher'
import { buildEditorialDraft } from '@/agents/editorialWriter'
import { applyIntegrityFindings } from '@/agents/integrityChecker'
import { buildMonitorEntry } from '@/agents/monitor'
import { enrichCategories, mergeConflicts } from '@/agents/scoreAnalyst'

/**
 * Phase G (G.5) — the five pipeline agents are rewired onto the real model
 * call (spec §5). These tests pin the safety mechanics that keep a real model
 * call inside the evidence discipline:
 * - parseJsonLoose: tolerant JSON extraction from model replies.
 * - No self-verification (QA S1-2 / spec test #10): confidence and
 *   verificationStatus can never leave `unverified`, no matter what the model
 *   returns.
 * - No fabrication (spec §0): a bare invented claim value drops to null unless
 *   it is grounded in the case context or carries a cited source URL.
 * - Editorial compliance block is deterministic (never model output).
 * - Integrity verdict is recomputed deterministically — model S0/S1 findings
 *   can only BLOCK, never PASS.
 * - Monitor never claims a live registry status (honesty pin).
 */

describe('llmBridge.parseJsonLoose', () => {
  it('parses plain JSON objects', () => {
    expect(parseJsonLoose('{"a": 1}')).toEqual({ a: 1 })
  })

  it('parses JSON inside markdown fences', () => {
    const text = '```json\n{"licensing": {"primary": {"value": null}}}\n```'
    expect(parseJsonLoose(text)).toEqual({ licensing: { primary: { value: null } } })
  })

  it('extracts the first object surrounded by prose', () => {
    const text = 'Here you go: {"ok": true, "nested": {"x": "}"}} and that is all.'
    expect(parseJsonLoose(text)).toEqual({ ok: true, nested: { x: '}' } })
  })

  it('returns null for non-JSON replies', () => {
    expect(parseJsonLoose('I cannot produce JSON right now.')).toBeNull()
    expect(parseJsonLoose(null)).toBeNull()
    expect(parseJsonLoose('{"broken": ')).toBeNull()
  })
})

describe('llmBridge.forceUnverifiedDiscipline (spec test #10)', () => {
  it('forces confidence + verificationStatus to unverified, even when the model claims otherwise', () => {
    const model = {
      licensing: { primary: { value: 'ABC-123', confidence: 'verified', sourceUrl: 'https://x.test' } },
      evidence: [{ verificationStatus: 'verified', capturedBy: 'model' }],
    }
    forceUnverifiedDiscipline(model, 'Generated by the desk-researcher agent — requires human confirmation.')
    expect(model.licensing.primary.confidence).toBe('unverified')
    expect((model.evidence[0] as Record<string, unknown>).verificationStatus).toBe('unverified')
  })

  it('fills empty unverifiedReason fields', () => {
    const model = { a: { confidence: 'unverified', unverifiedReason: null } }
    forceUnverifiedDiscipline(model, 'Human confirmation required.')
    expect(model.a.unverifiedReason).toBe('Human confirmation required.')
  })
})

describe('llmBridge no-invention guard', () => {
  const context = {
    operatorName: 'Stake',
    licenseNumber: 'GLH-OCCHSDW-19302017',
    licenseJurisdiction: 'Curacao',
  }

  it('keeps a claim value that cites its own source URL', () => {
    expect(guardClaimValue('2000 EUR', 'https://stake.example/bonus', new Set())).toBe('2000 EUR')
  })

  it('rejects a garbage sourceUrl — a fabricated citation cannot keep an invented value', () => {
    expect(guardClaimValue('FAKE-0001', 'not-a-url', new Set())).toBeNull()
    expect(guardClaimValue('FAKE-0001', '', new Set())).toBeNull()
  })

  it('keeps a value already present in the case context', () => {
    const values = contextValueSet(context)
    expect(guardClaimValue('GLH-OCCHSDW-19302017', null, values)).toBe('GLH-OCCHSDW-19302017')
  })

  it('drops a bare invented value with no source and no context support', () => {
    const values = contextValueSet(context)
    expect(guardClaimValue('GBL-99999999', null, values)).toBeNull()
  })

  it('applies the guard through claim-group merge', () => {
    const values = contextValueSet(context)
    const skeleton = { value: null, sourceUrl: null, confidence: 'unverified' }
    const merged = applyClaimGroup(skeleton, { value: 'GBL-99999999' }, values)
    expect(merged.value).toBeNull()
    const merged2 = applyClaimGroup(skeleton, { value: 'GLH-OCCHSDW-19302017' }, values)
    expect(merged2.value).toBe('GLH-OCCHSDW-19302017')
  })

  it('mergeSkeletonWithModel preserves the skeleton schema and drops invented values', () => {
    const values = contextValueSet(context)
    const skeleton = {
      licensing: { primary: { value: null, sourceUrl: null, confidence: 'unverified' } },
      provablyFair: { value: 'NO', confidence: 'unverified' },
    }
    const model = { licensing: { primary: { value: 'FAKE-0001' } } }
    const merged = mergeSkeletonWithModel(skeleton, model, values) as typeof skeleton
    expect(merged.licensing.primary.value).toBeNull()
    expect(merged.licensing.primary.confidence).toBe('unverified')
    expect(merged.provablyFair.value).toBe('NO')
  })

  it('buildEvidenceRegister keeps grounded rows (context value or source URL), all unverified', () => {
    const today = '2026-08-09'
    const parsed = {
      evidenceRegister: [
        { label: 'License', claimKey: 'licenseNumber', claimSummary: 'GLH-OCCHSDW-19302017', sourceUrl: null },
        { label: 'Bonus', claimKey: 'welcomeBonus', claimSummary: '2000 EUR welcome bonus', sourceUrl: 'https://stake.example/bonus' },
      ],
    }
    const rows = buildEvidenceRegister(parsed, contextValueSet(context), today)
    // row 1 grounded via the context license number; row 2 via its source URL
    expect(rows).toHaveLength(2)
    expect(rows.every((r) => r.verificationStatus === 'unverified')).toBe(true)
    expect(rows.every((r) => r.capturedBy === 'desk-researcher-agent')).toBe(true)
  })

  it('buildEvidenceRegister drops a completely invented row', () => {
    const fabricated = buildEvidenceRegister(
      { evidenceRegister: [{ label: 'Fake', claimKey: 'madeUpThing', claimSummary: 'totally invented claim', sourceUrl: null }] },
      contextValueSet(context),
      '2026-08-09',
    )
    expect(fabricated.every((r) => r.claimKey !== 'madeUpThing')).toBe(true)
  })
})

describe('editorialWriter.buildEditorialDraft (compliance pin)', () => {
  it('never lets model output change the compliance block', () => {
    const context = { operatorName: 'Stake', computedScores: { categories: [{ key: 'trust', score: 7 }] } }
    const parsed = {
      summary: 'Model summary',
      heroHeadline: 'Model headline',
      complianceBlock: { ageRequirement: 'NO WARNING' }, // hostile model attempt
    }
    const draft = buildEditorialDraft(context, parsed) as {
      summary: string
      complianceBlock: { ageRequirement: string; responsibleGamblingLinks: string[] }
      categoryBreakdown: unknown
    }
    expect(draft.summary).toBe('Model summary')
    expect(draft.complianceBlock.ageRequirement).toBe('18+ Only. Gambling can be addictive — play responsibly.')
    expect(draft.complianceBlock.responsibleGamblingLinks).toEqual([
      'https://www.begambleaware.org',
      'https://www.gamstop.co.uk',
    ])
    expect(draft.categoryBreakdown).toEqual([{ key: 'trust', score: 7 }])
  })

  it('falls back to deterministic copy when the model returns nothing', () => {
    const draft = buildEditorialDraft({ operatorName: 'Stake' }, null) as {
      summary: string
      complianceBlock: { ageRequirement: string }
    }
    expect(draft.summary).toContain('Stake')
    expect(draft.complianceBlock.ageRequirement).toContain('18+')
  })
})

describe('integrityChecker.applyIntegrityFindings (verdict semantics, reviewer S2)', () => {
  it('model S0/S1 findings force a BLOCK', () => {
    const { checksFailed, deterministicFailed, modelBlocking } = applyIntegrityFindings([], [
      { severity: 'S1', issue: 'Chase-loss phrasing in summary', domain: 'copy' },
    ])
    expect(modelBlocking).toBe(true)
    expect(checksFailed).toHaveLength(1)
    // verdict rule: PASS only when no code failure AND no S0/S1 model flag
    expect(deterministicFailed.length === 0 && !modelBlocking).toBe(false)
  })

  it('model S3 findings are advisory — they do not block (verdict stays PASS)', () => {
    const { checksFailed, deterministicFailed, modelBlocking } = applyIntegrityFindings([], [
      { severity: 'S3', issue: 'Minor tone nit', domain: 'copy' },
    ])
    expect(modelBlocking).toBe(false)
    expect(checksFailed).toHaveLength(1)
    expect(deterministicFailed.length === 0 && !modelBlocking).toBe(true)
  })

  it('keeps deterministic failures even when the model reports clean', () => {
    const { checksFailed, deterministicFailed, modelBlocking } = applyIntegrityFindings(
      ['Commission Wall Violation: x'],
      [],
    )
    expect(checksFailed).toHaveLength(1)
    expect(deterministicFailed).toHaveLength(1)
    expect(deterministicFailed.length === 0 && !modelBlocking).toBe(false)
  })
})

describe('scoreAnalyst enrich/merge', () => {
  const categories = [
    { key: 'trust', label: 'Trust', weight: 2, score: 5, conservative: true, pendingHandsOn: true, notes: 'default' },
  ]

  it('model rationale overrides the deterministic note for a matching key', () => {
    const out = enrichCategories(categories, { trust: 'Evidence-backed rationale' })
    expect(out[0].notes).toBe('Evidence-backed rationale')
    expect(out[0].score).toBe(5) // the score itself never comes from the model
  })

  it('merges conflicts deduped by field', () => {
    const merged = mergeConflicts(
      [{ field: 'a', claimed: '1', measured: '2', delta: 'x' }],
      [
        { field: 'a', claimed: '1', measured: '3', delta: 'dup' },
        { field: 'b', claimed: 'x', measured: 'y', delta: 'new' },
      ],
    )
    expect(merged.map((c) => c.field)).toEqual(['a', 'b'])
  })
})

describe('monitor.buildMonitorEntry (honesty pin)', () => {
  it('never claims a live registry status — defaults to CHECK_SCHEDULED', () => {
    const entry = buildMonitorEntry({ operatorName: 'Stake' }, null, new Date('2026-08-09T12:00:00Z'))
    expect(entry.result).toBe('CHECK_SCHEDULED')
    expect(entry.findings).toContain('verify license standing')
  })

  it('uses model prose when provided', () => {
    const entry = buildMonitorEntry(
      { operatorName: 'Stake' },
      { findings: 'Watch complaint spikes on AskGamblers.', watchList: ['Check AskGamblers', 'Check regulator DB'] },
    )
    expect(entry.findings).toBe('Watch complaint spikes on AskGamblers.')
    expect(entry.watchList).toHaveLength(2)
  })
})
