/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    'traditional-casino-reviews': TraditionalCasinoReview;
    'crypto-casino-reviews': CryptoCasinoReview;
    'wagering-bonuses': WageringBonus;
    'no-wagering-bonuses': NoWageringBonus;
    'agent-logs': AgentLog;
    operators: Operator;
    'research-queue': ResearchQueue;
    quests: Quest;
    'gamification-profiles': GamificationProfile;
    'user-quests': UserQuest;
    'xp-events': XpEvent;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'traditional-casino-reviews': TraditionalCasinoReviewsSelect<false> | TraditionalCasinoReviewsSelect<true>;
    'crypto-casino-reviews': CryptoCasinoReviewsSelect<false> | CryptoCasinoReviewsSelect<true>;
    'wagering-bonuses': WageringBonusesSelect<false> | WageringBonusesSelect<true>;
    'no-wagering-bonuses': NoWageringBonusesSelect<false> | NoWageringBonusesSelect<true>;
    'agent-logs': AgentLogsSelect<false> | AgentLogsSelect<true>;
    operators: OperatorsSelect<false> | OperatorsSelect<true>;
    'research-queue': ResearchQueueSelect<false> | ResearchQueueSelect<true>;
    quests: QuestsSelect<false> | QuestsSelect<true>;
    'gamification-profiles': GamificationProfilesSelect<false> | GamificationProfilesSelect<true>;
    'user-quests': UserQuestsSelect<false> | UserQuestsSelect<true>;
    'xp-events': XpEventsSelect<false> | XpEventsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    homepage: Homepage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  /**
   * Public media (site images) stays public. Mark evidence uploads "Internal" — anonymous requests cannot read internal media via the Payload API. Does not protect the raw static file URL (see collection doc comment).
   */
  visibility: 'public' | 'internal';
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "traditional-casino-reviews".
 */
export interface TraditionalCasinoReview {
  id: number;
  name: string;
  /**
   * Markets where this operator holds the required national license. Never list an operator here without one (spec.md).
   */
  markets: ('nl' | 'se' | 'de' | 'uk')[];
  compliance: {
    /**
     * Displayed on the page, not just linked (spec.md). Illustrative samples use an obviously-non-real SAMPLE-format.
     */
    licenseNumber: string;
    licenseAuthority: 'KSA' | 'Spelinspektionen' | 'GGL' | 'UKGC';
  };
  scores: {
    promotions: {
      /**
       * How exactly and completely bonus terms are stated — not just how generous
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    licensing: {
      /**
       * Current license status, past sanctions, complaint-resolution record
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    support: {
      /**
       * Channels, response time, resolution quality, language coverage
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    withdrawals: {
      /**
       * Methods offered, stated vs. actual processing time, any withdrawal caps
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    kyc: {
      /**
       * Speed, document requirements, clarity of what is needed upfront
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    gameVariety: {
      /**
       * Number and range of games, provider diversity, RTP transparency
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    deposits: {
      /**
       * Methods offered, minimums, processing speed, fees
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    liveCasino: {
      /**
       * Studio quality, dealer languages, table limits, uptime
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
  };
  /**
   * One-paragraph plain-language summary shown on listings.
   */
  summary: string;
  verdict: {
    whatsGood: {
      point: string;
      id?: string | null;
    }[];
    /**
     * Required, minimum one row — a review with nothing bad to say is not finished.
     */
    whatsBad: {
      point: string;
      id?: string | null;
    }[];
    narrative: string;
  };
  /**
   * Computed from category scores × rubric weights — never hand-set.
   */
  overallScore?: number | null;
  /**
   * Qualitative context only (grading-rubric.md "Qualitative context" section) — independent player sentiment, shown next to the score but never counted toward it. Deliberately a sibling of `scores`, not a member of it, so it is structurally impossible for computeOverallScore to read it.
   */
  communitySentimentNote?: string | null;
  /**
   * Renders a prominent "illustrative sample, not a real operator" banner. Stays on until a page describes a real onboarded operator with real logged evidence.
   */
  isIllustrativeSample?: boolean | null;
  /**
   * What the operator claims vs what our standardized hands-on tests actually measured. Leave measured blank until tested — never estimate.
   */
  claimsVsReality?: {
    withdrawal?: {
      /**
       * Stated processing time, in hours.
       */
      claimedHours?: number | null;
      /**
       * Actual elapsed time in the standardized withdrawal test, in hours.
       */
      measuredHours?: number | null;
    };
    support?: {
      /**
       * Stated response time, in minutes.
       */
      claimedMinutes?: number | null;
      /**
       * Time to first HUMAN response in the RG live-chat test, in minutes.
       */
      measuredMinutes?: number | null;
    };
    kyc?: {
      /**
       * Stated verification time, in days.
       */
      claimedDays?: number | null;
      /**
       * Actual approval time in the standardized KYC test, in days.
       */
      measuredDays?: number | null;
    };
    bonus?: {
      /**
       * Stated wagering requirement, e.g. 35 for 35×.
       */
      claimedWager?: number | null;
      /**
       * Actual wagering requirement faced in the standardized bonus test.
       */
      measuredWager?: number | null;
    };
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crypto-casino-reviews".
 */
export interface CryptoCasinoReview {
  id: number;
  name: string;
  compliance: {
    /**
     * Displayed on the page, verified against the live regulator register (spec.md). Illustrative samples use an obviously-non-real SAMPLE-format.
     */
    licenseNumber: string;
    /**
     * e.g. Curaçao GCB. Verified at scoring time, not onboarding.
     */
    licenseAuthority: string;
    /**
     * Must be checked — explicit statement this operator/content is not directed at NL/SE/DE/UK (spec.md hard exclusion).
     */
    notLicensedInRegulatedMarkets: boolean;
    /**
     * How a user can verify fairness themselves, if offered.
     */
    provablyFairInfo?: string | null;
  };
  scores: {
    licenseLegitimacy: {
      /**
       * Is the license real, current, and verifiable right now — not just claimed
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    promotions: {
      /**
       * Exact terms, no exceptions — same bar as Traditional
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    withdrawals: {
      /**
       * Crypto withdrawal speed, network fees, caps, fiat off-ramp options
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    kycApproach: {
      /**
       * Clarity and consistency of the stated policy — not strictness itself
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    provablyFair: {
      /**
       * Verifiable fairness a user can actually check, not just a claim
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    support: {
      /**
       * Channels, response time, resolution quality
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    deposits: {
      /**
       * Supported chains/coins, minimums, confirmation-time requirements
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    gameVariety: {
      /**
       * Range and quality of games and providers
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
    geoCompliance: {
      /**
       * Does the operator itself exclude the regulated markets we do
       */
      score: number;
      /**
       * Logged evidence reference — a number with no traceable source is not a valid score.
       */
      evidence: string;
      /**
       * The honest assessment for this category — what is actually good and actually bad.
       */
      narrative: string;
    };
  };
  /**
   * One-paragraph plain-language summary shown on listings.
   */
  summary: string;
  verdict: {
    whatsGood: {
      point: string;
      id?: string | null;
    }[];
    /**
     * Required, minimum one row — a review with nothing bad to say is not finished.
     */
    whatsBad: {
      point: string;
      id?: string | null;
    }[];
    narrative: string;
  };
  /**
   * Computed from category scores × rubric weights — never hand-set.
   */
  overallScore?: number | null;
  /**
   * Qualitative context only (grading-rubric.md "Qualitative context" section) — independent player sentiment, shown next to the score but never counted toward it. Deliberately a sibling of `scores`, not a member of it, so it is structurally impossible for computeOverallScore to read it.
   */
  communitySentimentNote?: string | null;
  /**
   * Renders a prominent "illustrative sample, not a real operator" banner. Stays on until a page describes a real onboarded operator with real logged evidence.
   */
  isIllustrativeSample?: boolean | null;
  /**
   * What the operator claims vs what our standardized hands-on tests actually measured. Leave measured blank until tested — never estimate.
   */
  claimsVsReality?: {
    withdrawal?: {
      /**
       * Stated processing time, in hours.
       */
      claimedHours?: number | null;
      /**
       * Actual elapsed time in the standardized withdrawal test, in hours.
       */
      measuredHours?: number | null;
    };
    support?: {
      /**
       * Stated response time, in minutes.
       */
      claimedMinutes?: number | null;
      /**
       * Time to first HUMAN response in the RG live-chat test, in minutes.
       */
      measuredMinutes?: number | null;
    };
    kyc?: {
      /**
       * Stated verification time, in days.
       */
      claimedDays?: number | null;
      /**
       * Actual approval time in the standardized KYC test, in days.
       */
      measuredDays?: number | null;
    };
    bonus?: {
      /**
       * Stated wagering requirement, e.g. 35 for 35×.
       */
      claimedWager?: number | null;
      /**
       * Actual wagering requirement faced in the standardized bonus test.
       */
      measuredWager?: number | null;
    };
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wagering-bonuses".
 */
export interface WageringBonus {
  id: number;
  title: string;
  /**
   * The reviewed operator this bonus belongs to.
   */
  operator: number | TraditionalCasinoReview;
  /**
   * Plain-language summary — the exact terms still live in the fields below.
   */
  summary: string;
  /**
   * Who qualifies — new players only, region restrictions, deposit method restrictions, etc.
   */
  eligibility: string;
  /**
   * Exact time limit to claim the bonus itself (separate from wagering clearance time, if applicable).
   */
  expiry: string;
  /**
   * Exact maximum withdrawal from bonus winnings, if capped. State "uncapped" explicitly if true — never leave blank.
   */
  maxWithdrawal: string;
  /**
   * Renders a prominent "illustrative sample, not a real offer" banner.
   */
  isIllustrativeSample?: boolean | null;
  /**
   * e.g. 35 for a 35x requirement.
   */
  wageringMultiplier: number;
  /**
   * What the multiplier is calculated against.
   */
  wageringAppliesTo: 'bonus_only' | 'bonus_plus_deposit';
  /**
   * Exact time limit to clear the wagering requirement, e.g. "30 days from credit".
   */
  wageringTimeLimit: string;
  /**
   * Which games count toward wagering, and at what rate — required per game category, not a blanket "all games".
   */
  contributingGames: {
    gameCategory: string;
    contributionPercent: number;
    id?: string | null;
  }[];
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "no-wagering-bonuses".
 */
export interface NoWageringBonus {
  id: number;
  title: string;
  /**
   * The reviewed operator this bonus belongs to.
   */
  operator: number | TraditionalCasinoReview;
  /**
   * Plain-language summary — the exact terms still live in the fields below.
   */
  summary: string;
  /**
   * Who qualifies — new players only, region restrictions, deposit method restrictions, etc.
   */
  eligibility: string;
  /**
   * Exact time limit to claim the bonus itself (separate from wagering clearance time, if applicable).
   */
  expiry: string;
  /**
   * Exact maximum withdrawal from bonus winnings, if capped. State "uncapped" explicitly if true — never leave blank.
   */
  maxWithdrawal: string;
  /**
   * Renders a prominent "illustrative sample, not a real offer" banner.
   */
  isIllustrativeSample?: boolean | null;
  /**
   * Exact amount or spins, e.g. "€25 no-deposit" or "50 free spins".
   */
  bonusAmount: string;
  /**
   * Even wager-free, winnings usually still have conditions before cashout (e.g. minimum deposit to unlock withdrawal, verification requirements). State them exactly, or state explicitly that none apply.
   */
  withdrawalConditions: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Append-only, immutable agent activity log (logging-spec.md). Server-generated only via logEvent() — no manual create, no update, no delete, ever; corrections must be new events (see correctsEventId). Compliance-relevant events (grades, QA checks, publish/unpublish, license rechecks, case creation/status transitions/material updates) are retained indefinitely; operational events are not.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-logs".
 */
export interface AgentLog {
  id: number;
  event:
    | 'research_fetch'
    | 'draft_created'
    | 'draft_edited'
    | 'grade_assigned'
    | 'qa_check'
    | 'publish'
    | 'unpublish'
    | 'license_recheck'
    | 'case_created'
    | 'status_transition'
    | 'case_updated';
  timestamp: string;
  agentId: string;
  /**
   * e.g. '01-playerside' (ORG.md brand directory naming).
   */
  brand: string;
  /**
   * Category within the brand, e.g. 'traditional' or 'crypto-casino'. Kept distinct from rubricCategory (logging-spec.md field naming note).
   */
  siteCategory?: string | null;
  operator?: string | null;
  pageId?: string | null;
  rubricCategory?: string | null;
  score?: number | null;
  /**
   * Link to the research fetch or source that justifies a grade_assigned event. Required whenever event is grade_assigned — enforced by hook, not just this description.
   */
  evidenceRef?: string | null;
  /**
   * The id of the agent-logs event this one corrects, if any. Since entries are immutable, a correction is always a new event referencing the one it supersedes — never an edit.
   */
  correctsEventId?: string | null;
  /**
   * Event-specific fields per logging-spec.md: source_url/extracted (research fetch), draft_version/inputs_used (draft events), qa_checks (per-field pass/fail + reason), qa_check_ref (publish/unpublish), previous_status/current_status/source_checked (license recheck).
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Computed from event type on every save — never hand-set.
   */
  retentionClass?: ('compliance' | 'operational') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators".
 */
export interface Operator {
  id: number;
  name: string;
  slug: string;
  jurisdiction?: string | null;
  incorporationCountry?: string | null;
  /**
   * Every case (brand) known to belong to this operator — kept in sync automatically when a case sets this operator as its parentCompany (§8.1).
   */
  knownBrands?: (number | ResearchQueue)[] | null;
  /**
   * Scandals, legal actions, press coverage — internal only, never auto-published (§8.2).
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Flags this operator for active regulatory monitoring (Monitor agent, MONITOR.md).
   */
  regulatoryWatchFlag?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Review Intelligence System case files (MASTER-BLUEPRINT.md §3). Referred to as "Case File" in agent role docs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-queue".
 */
export interface ResearchQueue {
  id: number;
  /**
   * Format #PS-YYYY-NNN (real cases) or #PS-YYYY-SNN (seed/illustrative cases) — §2.
   */
  caseNumber: string;
  operatorName: string;
  operatorUrl?: string | null;
  casinoType: 'traditional' | 'crypto';
  /**
   * The Operator (parent/holding company) this brand belongs to (§8.1).
   */
  parentCompany?: (number | null) | Operator;
  licenseJurisdiction?: string | null;
  licenseNumber?: string | null;
  status:
    'queued' | 'desk-research' | 'hands-on-testing' | 'editorial' | 'integrity-check' | 'published' | 'monitoring';
  assignedReviewer?: string | null;
  /**
   * Optimistic-concurrency token (docs/review-handoffs/2026-07-23-research-queue-concurrency-spec.md §3.1) — bumped atomically by enforceOptimisticVersion.ts on every update. Not editorial data; never set this by hand.
   */
  version?: number | null;
  /**
   * Populated by the Desk Researcher agent (DESK-RESEARCHER.md output format).
   */
  deskResearchOutput?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  handsOnResults?: {
    withdrawalClaimedHours?: number | null;
    withdrawalActualHours?: number | null;
    withdrawalEvidenceRef?: (number | null) | Media;
    /**
     * Operator-claimed live chat response time.
     */
    supportClaimedMinutes?: number | null;
    /**
     * Live chat (RG test, TEST-CASES.md §Channel 1) — time to first human response.
     */
    supportActualMinutes?: number | null;
    supportEvidenceRef?: (number | null) | Media;
    /**
     * Sub-questions answered by the RG live chat test (TEST-CASES.md §Channel 1).
     */
    supportQualityScore?: ('0' | '1' | '2' | '3') | null;
    supportEmpathyFlag?: boolean | null;
    supportRGResourcesFlag?: boolean | null;
    /**
     * Email (KYC/privacy test, TEST-CASES.md §Channel 2) — time to first response, in hours.
     */
    emailSupportActualHours?: number | null;
    /**
     * Sub-questions answered by the KYC/privacy email test (TEST-CASES.md §Channel 2).
     */
    emailQualityScore?: ('0' | '1' | '2' | '3') | null;
    emailGDPRFlag?: boolean | null;
    /**
     * Desk Researcher cross-check: does the stated retention period match the live Privacy Policy? (TEST-CASES.md §Cross-check)
     */
    emailPolicyAccuracyFlag?: ('match' | 'conflict' | 'not-checked') | null;
    kycClaimedDays?: number | null;
    kycActualDays?: number | null;
    kycEvidenceRef?: (number | null) | Media;
    bonusClaimedWager?: number | null;
    bonusActualWager?: number | null;
    bonusEvidenceRef?: (number | null) | Media;
  };
  /**
   * Populated by the Score Analyst agent (SCORE-ANALYST.md output format).
   */
  computedScores?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Populated by the Editorial Writer agent — draft until Viktor + Integrity Checker sign off.
   */
  editorialDraft?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Set once the Integrity Checker agent output is INTEGRITY: PASS and Viktor confirms.
   */
  integritySignOff?: boolean | null;
  /**
   * The live review this case became, once published.
   */
  publishedReviewId?:
    | ({
        relationTo: 'traditional-casino-reviews';
        value: number | TraditionalCasinoReview;
      } | null)
    | ({
        relationTo: 'crypto-casino-reviews';
        value: number | CryptoCasinoReview;
      } | null);
  /**
   * Never published — internal case notes only.
   */
  internalNotes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Monitor agent entries post-publish (MONITOR.md).
   */
  monitorLog?:
    | {
        date: string;
        flagType: string;
        summary: string;
        agentRef?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Structured evidence register — every fact this case relies on should trace to one entry here, sourced and labelled (DESK-RESEARCHER.md confidence convention). Each row has a real Payload-generated id; supersedesEvidenceId references that id to build a correction lineage.
   */
  evidenceRegister?:
    | {
        /**
         * What this evidence supports or verifies.
         */
        label: string;
        /**
         * Short identifier for the specific claim this evidence backs, e.g. "licenseNumber" or "withdrawalSpeed".
         */
        claimKey?: string | null;
        /**
         * The claim itself, in plain language.
         */
        claimSummary?: string | null;
        /**
         * What kind of source this is (DESK-RESEARCHER.md sourcing rules).
         */
        sourceType?:
          ('regulator-register' | 'operator-primary' | 'community-source' | 'hands-on-test' | 'other') | null;
        /**
         * Screenshot or upload, if applicable.
         */
        mediaRef?: (number | null) | Media;
        /**
         * Direct URL to the source, if applicable (e.g. regulator register page).
         */
        sourceUrl?: string | null;
        /**
         * Archive permalink (e.g. Wayback Machine), where practical.
         */
        archiveRef?: string | null;
        /**
         * Hash of the captured content, for integrity verification, where practical.
         */
        contentHash?: string | null;
        /**
         * When the researcher reviewed/verified the source.
         */
        accessDate?: string | null;
        /**
         * When the evidence artifact itself (screenshot, log) was captured — may differ from accessDate.
         */
        capturedAt?: string | null;
        /**
         * Who or what captured this evidence — a name or agent id.
         */
        capturedBy?: string | null;
        verificationStatus: 'verified' | 'corroborated' | 'unverified';
        /**
         * Whether this is still the active evidence for its claimKey, or has been superseded.
         */
        isCurrent?: boolean | null;
        /**
         * The id of the evidence row this entry replaces, if any (correction lineage).
         */
        supersedesEvidenceId?: string | null;
        /**
         * Why this evidence was retracted/superseded, if applicable.
         */
        retractionReason?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal-only test-account metadata (CREDENTIAL-LOG.md). Never store passwords, 2FA seeds, or other secrets here — password manager only. This group holds labels/identifiers, not credentials.
   */
  accountProfile?: {
    /**
     * A description of the account used — never a username or password.
     */
    liveChatAccountLabel?: string | null;
    /**
     * The clean test address for the email channel, per CREDENTIAL-LOG.md convention.
     */
    emailTestAddress?: string | null;
    accountStatus?: ('active' | 'suspended' | 'closed' | 'not-created') | null;
    notes?: string | null;
  };
  /**
   * Versioned AI agent run records for this case (§10 data-model foundation only — no chat route, provider integration, or frontend UI exists yet; nothing writes here).
   */
  aiRuns?:
    | {
        /**
         * Unique identifier for this run.
         */
        runId: string;
        agentRole: 'desk-researcher' | 'score-analyst' | 'editorial-writer' | 'integrity-checker' | 'monitor' | 'chat';
        version: number;
        status: 'pending' | 'complete' | 'failed';
        startedAt?: string | null;
        completedAt?: string | null;
        /**
         * What was sent to the agent for this run.
         */
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * What the agent returned for this run.
         */
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Turn-by-turn record for this run.
         */
        messages?:
          | {
              role: 'user' | 'assistant' | 'system';
              content: string;
              timestamp: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests".
 */
export interface Quest {
  id: number;
  /**
   * Stable machine id, e.g. bonus_hunter. Unique per mission.
   */
  missionId: string;
  title: string;
  /**
   * One-paragraph player-facing brief (vex-canon copy).
   */
  brief: string;
  /**
   * XP minted once, server-side, on full completion.
   */
  rewardXp: number;
  /**
   * Where this mission can be offered.
   */
  pageTarget: 'casino-review' | 'crypto-review' | 'homepage';
  /**
   * Feature flag for this mission (vex_enabled).
   */
  enabled?: boolean | null;
  /**
   * QuestStep[] JSON — { kind: "quiz", options, correctKey, rgExplain } or { kind: "wagering_math", bonusSlug, depositAmount, options, rgExplain }. Answers are validated by src/gamification/validators.ts.
   */
  steps:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gamification-profiles".
 */
export interface GamificationProfile {
  id: number;
  /**
   * Client-generated anonymous identity (UUID).
   */
  playerKey: string;
  /**
   * Cached aggregate; source of truth is xp-events (append-only).
   */
  totalXp: number;
  /**
   * Recomputed from totalXp via xp_required(L) = floor(100*L^1.5).
   */
  level: number;
  /**
   * Canon ladder title for the current level (vex-canon flavor).
   */
  rankTitle?: string | null;
  completedMissions?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-quests".
 */
export interface UserQuest {
  id: number;
  /**
   * Anonymous player identity.
   */
  playerKey: string;
  /**
   * The mission definition.
   */
  quest: number | Quest;
  status: 'offered' | 'active' | 'completed';
  /**
   * Next unanswered step (0-based).
   */
  stepIndex?: number | null;
  /**
   * Last processed idempotency key (dedup guard).
   */
  lastEvidenceId?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "xp-events".
 */
export interface XpEvent {
  id: number;
  /**
   * Anonymous player identity.
   */
  playerKey: string;
  /**
   * XP minted. NEVER updated after insert.
   */
  amount: number;
  reason: 'mission_completed' | 'badge_granted';
  quest?: (number | null) | Quest;
  /**
   * Idempotency key — (playerKey, evidenceId) must be unique.
   */
  evidenceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'traditional-casino-reviews';
        value: number | TraditionalCasinoReview;
      } | null)
    | ({
        relationTo: 'crypto-casino-reviews';
        value: number | CryptoCasinoReview;
      } | null)
    | ({
        relationTo: 'wagering-bonuses';
        value: number | WageringBonus;
      } | null)
    | ({
        relationTo: 'no-wagering-bonuses';
        value: number | NoWageringBonus;
      } | null)
    | ({
        relationTo: 'agent-logs';
        value: number | AgentLog;
      } | null)
    | ({
        relationTo: 'operators';
        value: number | Operator;
      } | null)
    | ({
        relationTo: 'research-queue';
        value: number | ResearchQueue;
      } | null)
    | ({
        relationTo: 'quests';
        value: number | Quest;
      } | null)
    | ({
        relationTo: 'gamification-profiles';
        value: number | GamificationProfile;
      } | null)
    | ({
        relationTo: 'user-quests';
        value: number | UserQuest;
      } | null)
    | ({
        relationTo: 'xp-events';
        value: number | XpEvent;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "traditional-casino-reviews_select".
 */
export interface TraditionalCasinoReviewsSelect<T extends boolean = true> {
  name?: T;
  markets?: T;
  compliance?:
    | T
    | {
        licenseNumber?: T;
        licenseAuthority?: T;
      };
  scores?:
    | T
    | {
        promotions?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        licensing?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        support?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        withdrawals?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        kyc?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        gameVariety?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        deposits?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        liveCasino?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
      };
  summary?: T;
  verdict?:
    | T
    | {
        whatsGood?:
          | T
          | {
              point?: T;
              id?: T;
            };
        whatsBad?:
          | T
          | {
              point?: T;
              id?: T;
            };
        narrative?: T;
      };
  overallScore?: T;
  communitySentimentNote?: T;
  isIllustrativeSample?: T;
  claimsVsReality?:
    | T
    | {
        withdrawal?:
          | T
          | {
              claimedHours?: T;
              measuredHours?: T;
            };
        support?:
          | T
          | {
              claimedMinutes?: T;
              measuredMinutes?: T;
            };
        kyc?:
          | T
          | {
              claimedDays?: T;
              measuredDays?: T;
            };
        bonus?:
          | T
          | {
              claimedWager?: T;
              measuredWager?: T;
            };
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crypto-casino-reviews_select".
 */
export interface CryptoCasinoReviewsSelect<T extends boolean = true> {
  name?: T;
  compliance?:
    | T
    | {
        licenseNumber?: T;
        licenseAuthority?: T;
        notLicensedInRegulatedMarkets?: T;
        provablyFairInfo?: T;
      };
  scores?:
    | T
    | {
        licenseLegitimacy?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        promotions?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        withdrawals?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        kycApproach?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        provablyFair?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        support?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        deposits?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        gameVariety?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
        geoCompliance?:
          | T
          | {
              score?: T;
              evidence?: T;
              narrative?: T;
            };
      };
  summary?: T;
  verdict?:
    | T
    | {
        whatsGood?:
          | T
          | {
              point?: T;
              id?: T;
            };
        whatsBad?:
          | T
          | {
              point?: T;
              id?: T;
            };
        narrative?: T;
      };
  overallScore?: T;
  communitySentimentNote?: T;
  isIllustrativeSample?: T;
  claimsVsReality?:
    | T
    | {
        withdrawal?:
          | T
          | {
              claimedHours?: T;
              measuredHours?: T;
            };
        support?:
          | T
          | {
              claimedMinutes?: T;
              measuredMinutes?: T;
            };
        kyc?:
          | T
          | {
              claimedDays?: T;
              measuredDays?: T;
            };
        bonus?:
          | T
          | {
              claimedWager?: T;
              measuredWager?: T;
            };
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wagering-bonuses_select".
 */
export interface WageringBonusesSelect<T extends boolean = true> {
  title?: T;
  operator?: T;
  summary?: T;
  eligibility?: T;
  expiry?: T;
  maxWithdrawal?: T;
  isIllustrativeSample?: T;
  wageringMultiplier?: T;
  wageringAppliesTo?: T;
  wageringTimeLimit?: T;
  contributingGames?:
    | T
    | {
        gameCategory?: T;
        contributionPercent?: T;
        id?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "no-wagering-bonuses_select".
 */
export interface NoWageringBonusesSelect<T extends boolean = true> {
  title?: T;
  operator?: T;
  summary?: T;
  eligibility?: T;
  expiry?: T;
  maxWithdrawal?: T;
  isIllustrativeSample?: T;
  bonusAmount?: T;
  withdrawalConditions?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-logs_select".
 */
export interface AgentLogsSelect<T extends boolean = true> {
  event?: T;
  timestamp?: T;
  agentId?: T;
  brand?: T;
  siteCategory?: T;
  operator?: T;
  pageId?: T;
  rubricCategory?: T;
  score?: T;
  evidenceRef?: T;
  correctsEventId?: T;
  details?: T;
  retentionClass?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators_select".
 */
export interface OperatorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  jurisdiction?: T;
  incorporationCountry?: T;
  knownBrands?: T;
  internalNotes?: T;
  regulatoryWatchFlag?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-queue_select".
 */
export interface ResearchQueueSelect<T extends boolean = true> {
  caseNumber?: T;
  operatorName?: T;
  operatorUrl?: T;
  casinoType?: T;
  parentCompany?: T;
  licenseJurisdiction?: T;
  licenseNumber?: T;
  status?: T;
  assignedReviewer?: T;
  version?: T;
  deskResearchOutput?: T;
  handsOnResults?:
    | T
    | {
        withdrawalClaimedHours?: T;
        withdrawalActualHours?: T;
        withdrawalEvidenceRef?: T;
        supportClaimedMinutes?: T;
        supportActualMinutes?: T;
        supportEvidenceRef?: T;
        supportQualityScore?: T;
        supportEmpathyFlag?: T;
        supportRGResourcesFlag?: T;
        emailSupportActualHours?: T;
        emailQualityScore?: T;
        emailGDPRFlag?: T;
        emailPolicyAccuracyFlag?: T;
        kycClaimedDays?: T;
        kycActualDays?: T;
        kycEvidenceRef?: T;
        bonusClaimedWager?: T;
        bonusActualWager?: T;
        bonusEvidenceRef?: T;
      };
  computedScores?: T;
  editorialDraft?: T;
  integritySignOff?: T;
  publishedReviewId?: T;
  internalNotes?: T;
  monitorLog?:
    | T
    | {
        date?: T;
        flagType?: T;
        summary?: T;
        agentRef?: T;
        id?: T;
      };
  evidenceRegister?:
    | T
    | {
        label?: T;
        claimKey?: T;
        claimSummary?: T;
        sourceType?: T;
        mediaRef?: T;
        sourceUrl?: T;
        archiveRef?: T;
        contentHash?: T;
        accessDate?: T;
        capturedAt?: T;
        capturedBy?: T;
        verificationStatus?: T;
        isCurrent?: T;
        supersedesEvidenceId?: T;
        retractionReason?: T;
        notes?: T;
        id?: T;
      };
  accountProfile?:
    | T
    | {
        liveChatAccountLabel?: T;
        emailTestAddress?: T;
        accountStatus?: T;
        notes?: T;
      };
  aiRuns?:
    | T
    | {
        runId?: T;
        agentRole?: T;
        version?: T;
        status?: T;
        startedAt?: T;
        completedAt?: T;
        input?: T;
        output?: T;
        messages?:
          | T
          | {
              role?: T;
              content?: T;
              timestamp?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quests_select".
 */
export interface QuestsSelect<T extends boolean = true> {
  missionId?: T;
  title?: T;
  brief?: T;
  rewardXp?: T;
  pageTarget?: T;
  enabled?: T;
  steps?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gamification-profiles_select".
 */
export interface GamificationProfilesSelect<T extends boolean = true> {
  playerKey?: T;
  totalXp?: T;
  level?: T;
  rankTitle?: T;
  completedMissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-quests_select".
 */
export interface UserQuestsSelect<T extends boolean = true> {
  playerKey?: T;
  quest?: T;
  status?: T;
  stepIndex?: T;
  lastEvidenceId?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "xp-events_select".
 */
export interface XpEventsSelect<T extends boolean = true> {
  playerKey?: T;
  amount?: T;
  reason?: T;
  quest?: T;
  evidenceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroEyebrow?: string | null;
  heroHeadline?: string | null;
  heroSubhead?: string | null;
  heroPrimaryCtaLabel?: string | null;
  heroPrimaryCtaHref?: string | null;
  heroSecondaryCtaLabel?: string | null;
  heroSecondaryCtaHref?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sampleOperators?:
    | {
        name: string;
        market: string;
        score: number;
        evidenceNote: string;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaSubtext?: string | null;
  ctaButtonLabel?: string | null;
  ctaButtonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeadline?: T;
  heroSubhead?: T;
  heroPrimaryCtaLabel?: T;
  heroPrimaryCtaHref?: T;
  heroSecondaryCtaLabel?: T;
  heroSecondaryCtaHref?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sampleOperators?:
    | T
    | {
        name?: T;
        market?: T;
        score?: T;
        evidenceNote?: T;
        id?: T;
      };
  ctaHeading?: T;
  ctaSubtext?: T;
  ctaButtonLabel?: T;
  ctaButtonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}